on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-18.04
    env:
      MONGODB_URL: mongodb://localhost:27017/authal_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - run: pip3 install poetry==0.12.17
      - run: poetry install -n
      - run: make test
